### ISSUE TITLE
Should this be 'template' instead of 'div'?

### ISSUE THREAD

**Issue by M3S8** [caolan/magery-tests#1]
https://github.com/caolan/magery-tests/blob/c6d512c8272671c13a7846472efd344e5efe022b/components/0901-component-with-child-expansion/template.html#L6

**Comment by caolan** [comment]
Yes, my tools are too smart and shield me from my own stupidity. Thanks :)

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/12
