### ISSUE TITLE
Other representations of boolean attributes?

### ISSUE THREAD

**Issue by M3S8** [caolan/magery-tests#2]
I'm seeing some issues where some html parsers can't produce this:

https://github.com/caolan/magery-tests/blob/master/components/0610-boolean-property-disabled/expected.html#L2

Any suggestions how to still incorporate these tests and in a server side implementation that doesn't produce this exactly, but will still be compliant according to the following? :

https://html.spec.whatwg.org/#boolean-attributes

**Comment by M3S8** [comment]
For example, one library I am working with will read this in and set the value to be the name of the attribute in the internal representation.

The library, "as is", will only allow quoted value or an empty quoted string as values when you turn around to output it, which both appear to be compliant with the spec for boolean attributes.

**Comment by M3S8** [comment]
Never mind, I think I figured it out, maybe I was thinking about it in the wrong way.

As long as I am doing the comparison against the same parser results, it should be OK, it seems compliant even if it can't produce that exact output.

**Comment by caolan** [comment]
Yes, for the record, producing template results which are semantically equivalent is fine. It's not necessary to exactly match the expected output as a string.

@mattschlobohm sorry I missed this issue, I forgot to turn on notifications for this repository. Are you still working on an implementation?

Closing this since you seem to have solved the issue.

**Comment by M3S8** [comment]
@caolan yes, I'm working on an implementation in Elixir as I find spare moments to do so.

**Comment by caolan** [comment]
@mattschlobohm nice :) good luck with it.

If you have any questions feel free to open an issue here, and I'll actually get back to you this time!
