### ISSUE TITLE
0112-variable-substitution-undefined trucate space

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#3]
In the expected results of 0112-variable-substitution-undefined I think there should be a space after the comma.
If I'm wrong please explain why we should not garantee this.

**Comment by benzen** [comment]
I've noticed the same problem with 0111-variable-substitution-null.

This in my opinion is in contradiction with the behavior expected in 0104-missing-nested-property.
Where the space before the null variable is remove, but the character after the variable is a \n

**Comment by benzen** [comment]
Here we can see that js implementation output the same result
https://github.com/caolan/magery/blob/master/test/test-compile.js#L127

**Comment by caolan** [comment]
Yes, I think there should be a space after the comma in this case.

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/14
