### ISSUE TITLE
Add error message to the tests

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#4]
When using a templating system i often encounter error about formatting of the template or data format.

What if we add standard error message when the template is badly formatted ?
This would make developper transition smoother between backend and front end.

How do you feel about this kind of idea?

**Comment by caolan** [comment]
Yes, sounds good. I've been planning to add failing cases to this test suite instead of just passing examples, so we can attempt to standardise error cases too.

**Comment by benzen** [comment]
Here are the case I encourter where i think an error message would be helpfull.

1-  Calling a never defined template (either directly as the root, or indirectly by one of the child component)
2- badly formatted text or attribute (eg "abc {{variable" or "abc variable}}")
3- rendering a the top component inside an element that doesn't hold the same name

**Comment by caolan** [comment]
I think we should also have an error message for `data-if="{{ variable }}"` instead of the correct `data-if="variable"` - it's easy to mix the syntax up and get confused as to why the template isn't rendering as you expect. This would also need adding for `data-unless`,

**Comment by caolan** [comment]
And another error test case for badly named components, e.g. forgetting to include the '-' required by HTML5 custom tags.

**Comment by benzen** [comment]
Overriding a template name (P.ex defining two template "app-button" ) ?

**Comment by caolan** [comment]
Yes, that makes sense.

**Comment by benzen** [comment]
I want to make error message make clear for the user.
I'd like to replace the kind of message with (when possible) message like this

```shell
In file: /groovy-magery/target/test-classes/magery-tests/components/3014-too-many-closing-curly-braces-on-attribute/template.html
At line: 1
Variables should be escape between "{{" and "}}"
<a href="{{ def">link</a>
         ^^^^^^^^^^^^^^^^
```

Is this something valuable in your opinion ?.
For 5 error cases already defined it's pretty easy to implement.
But maybe it's a bit early in the project to for other implementer to pay attention to this kind of details.

**Comment by caolan** [comment]
I think better error messages as standard is a good idea! I suggest we don't make matching the error message a requirement for every implementation though.

Perhaps we should __require__ that every implementation reports an error, and __recommend__ that the error matches the message in the test suite?

**Comment by benzen** [comment]
Interesting.
Let's take the case 3014, what do you propose as form of recommendation ?

**Comment by caolan** [comment]
I think what you've recommended looks good. We'd have to be careful with paths in the test suite of course, perhaps use a relative path from the magery-tests directory? I'd also have the `^^^^^^^^^` underline just cover the attribute value (between quotes).

The line number in the source file is important, that way IDEs could highlight errors for you.
