### ISSUE TITLE
Why is the doctype required in this exemple ?

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#5]
https://github.com/caolan/magery-tests/blob/c6d512c8272671c13a7846472efd344e5efe022b/components/0406-data-each-before-data-if/expected.html#L1
  
and
https://github.com/caolan/magery-tests/blob/c6d512c8272671c13a7846472efd344e5efe022b/components/0406-data-each-before-data-if/expected.html#L1

and

https://github.com/caolan/magery-tests/blob/c6d512c8272671c13a7846472efd344e5efe022b/components/0004-html-comments/expected.html#L1

**Comment by caolan** [comment]
I suspect it was a quick fix for some issues I had with the html parsing library used in the python bindings. I'll review with a look to removing these.

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/16
