### ISSUE TITLE
why remove comments line in 0004-html-comments ?

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#6]
In 0004-html-comments, the line that contains comments.
I think the comments should be passed as straight text (escaped of course).

Plus on this test, the empty (space only) line is completely removed.
If we keep removing the comments, at least text  node arround the comment should be kept, in my opinion.

**Comment by caolan** [comment]
Agreed. There are going to be cases where people will want to deliver comments to the client so we should support it. It may also be desirable to have non-rendered comments in future, but we may have to use a custom magery tag for that.

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/9
