### ISSUE TITLE
About self closing tags

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#8]
I see i distint behavior in regards to self closing tags
0105-underscore-variable-in-attribute and  0603-boolean-property-autofocus.
In one case we close the the image tag, on the other we don't  close the input tag.

I think the comportment should be made consistent on this point

**Comment by caolan** [comment]
Looking at the python implementation it looks like I standardised on no forward slash at the end of self-closing tags. My python test runner does not do direct string comparisons, and compares the parsed HTML results instead, so small changes like this were probably not caught.

I suggest we standardise on no forward-slash at the end of self-closing tags as it is marginally easier to implement.

**Comment by benzen** [comment]
Agreed

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/11
